In [21]:
import pandas as pd
import hashlib

data = pd.read_csv("C:/Users/SAI NITISH/OneDrive/Desktop/bosch_project2/data/product_quality_data.csv")
data.head()

,Product_ID,Batch_ID,Component_Type,Supplier_ID,Inspection_Score,Packaging_Integrity,Serialization_Status
0,P301-01,BATCH_301,Brake_Pad,SUPP_A,92,Yes,Yes
1,P301-02,BATCH_301,Brake_Pad,SUPP_A,90,Yes,Yes
2,P301-03,BATCH_301,Brake_Pad,SUPP_A,88,Yes,Yes
3,P301-04,BATCH_301,Brake_Pad,SUPP_A,91,Yes,Yes
4,P301-05,BATCH_301,Brake_Pad,SUPP_A,89,Yes,Yes

In [22]:
data.tail()

,Product_ID,Batch_ID,Component_Type,Supplier_ID,Inspection_Score,Packaging_Integrity,Serialization_Status
95,P310-06,BATCH_310,Timing_Belt,SUPP_J,71,No,No
96,P310-07,BATCH_310,Timing_Belt,SUPP_J,77,No,Yes
97,P310-08,BATCH_310,Timing_Belt,SUPP_J,73,No,No
98,P310-09,BATCH_310,Timing_Belt,SUPP_J,76,No,Yes
99,P310-10,BATCH_310,Timing_Belt,SUPP_J,72,No,No

In [23]:
def check_product_authenticity(row):
    if row["Packaging_Integrity"] == "No" or row["Serialization_Status"] == "No":
        return "Counterfeit"
    elif row["Inspection_Score"] < 75:
        return "Genuine - High Risk"
    else:
        return "Genuine - Low Risk"

In [24]:
def generate_blockchain_hash(row, authenticity_status):

    record = (
        row["Product_ID"]
        + row["Batch_ID"]
        + row["Component_Type"]
        + row["Supplier_ID"]
        + str(row["Inspection_Score"])
        + row["Packaging_Integrity"]
        + row["Serialization_Status"]
        + authenticity_status
    )

    return hashlib.sha256(record.encode()).hexdigest()

In [25]:
product_id = "P302-04"   # change this to test

row = data[data["Product_ID"] == product_id]

if row.empty:
    print("❌ Product not found")
else:
    row = row.iloc[0]

    status = check_product_authenticity(row)
    blockchain_hash = generate_blockchain_hash(row, status)

    print("Product ID:", row["Product_ID"])
    print("Batch ID:", row["Batch_ID"])
    print("Component Type:", row["Component_Type"])
    print("Supplier ID:", row["Supplier_ID"])
    print("Inspection Score:", row["Inspection_Score"])
    print("Packaging Integrity:", row["Packaging_Integrity"])
    print("Serialization Status:", row["Serialization_Status"])
    print("Authenticity Status:", status)
    print("Blockchain Hash:", blockchain_hash)

Product ID: P302-04
Batch ID: BATCH_302
Component Type: Sensor_Module
Supplier ID: SUPP_B
Inspection Score: 62
Packaging Integrity: No
Serialization Status: No
Authenticity Status: Counterfeit
Blockchain Hash: e40923bb1cd2bcb90800c12c75db9d88e6ee2ce339112f3c0b42a6f9b3ccb395

In [26]:
for _, row in data.head(5).iterrows():
    status = check_product_authenticity(row)
    hash_value = generate_blockchain_hash(row, status)

    print(row["Product_ID"], "→", status)
    print("Hash:", hash_value)
    print("-" * 50)

P301-01 → Genuine - Low Risk
Hash: 36a862754d0dbd32d53c5a3bf74d26d2d72dd82d258234904b9b4f37a8412611
--------------------------------------------------
P301-02 → Genuine - Low Risk
Hash: 07de63065e04dcf836afa15acda22a511f8d4caa1d448f1ce90524b0b2c09826
--------------------------------------------------
P301-03 → Genuine - Low Risk
Hash: 287a1fb7df151febb903538e8a5e871b7b029f587d7762de497d3c3503d5acd1
--------------------------------------------------
P301-04 → Genuine - Low Risk
Hash: d01b96c306239fc2ba80bb95b13fb61a8fadbc7398b5bf7f0148d65ebc9fea49
--------------------------------------------------
P301-05 → Genuine - Low Risk
Hash: 7dbc5d5d537e57f8a10105d862686da2534c609ae737d5d3169552eabe581075
--------------------------------------------------

In [27]:
for _, row in data.tail(5).iterrows():
    status = check_product_authenticity(row)
    hash_value = generate_blockchain_hash(row, status)

    print(row["Product_ID"], "→", status)
    print("Hash:", hash_value)
    print("-" * 50)

P310-06 → Counterfeit
Hash: 865a36c7af3017ceaf9712b3d165ed43640b1b5f447c89667424739ed3880172
--------------------------------------------------
P310-07 → Counterfeit
Hash: 0d926cc5c28524e0ad84d6d4a90d601df3a880c1cd95afae5b42cc6fbd00d341
--------------------------------------------------
P310-08 → Counterfeit
Hash: 33b061d55b88d2604402ff5a32865a91da8d8a6df195ecaecca08b333042769b
--------------------------------------------------
P310-09 → Counterfeit
Hash: 82b276eb2bada6f22938789f52a08fdf49f6345975e6722d744b833647b13d65
--------------------------------------------------
P310-10 → Counterfeit
Hash: e4acd8c35c5b5d14f20f715b0d6282b26aee3ac4c23be308807b59b115bdafe9
--------------------------------------------------

In [ ]:
py -m streamlit run app.py